Update Shell Script to ping URL

diff --git a/Shell Script to ping URL b/Shell Script to ping URL
--- a/Shell Script to ping URL
+++ b/Shell Script to ping URL
@@ -29,3 +29,30 @@ if [ "$HTTP_STATUS" -eq 200 ]; then
 else
     echo "URL is not reachable. Status: $HTTP_STATUS"
 fi
+
+
+Forloop for multiple server
+
+#!/bin/bash
+
+# List of remote servers to be pinged
+REMOTE_SERVERS=("www.guvi.in" "www.google.com" "www.github.com")
+
+# Number of pings to be sent
+PING_COUNT=4
+
+# Loop through each remote server
+for SERVER in "${REMOTE_SERVERS[@]}"; do
+    echo "Pinging $SERVER..."
+    
+    # Ping the remote server
+    ping -c "$PING_COUNT" "$SERVER" > /dev/null 2>&1
+    
+    # Check the exit status of the ping command
+    if [ $? -eq 0 ]; then
+        echo "Server $SERVER is reachable."
+    else
+        echo "Server $SERVER is not reachable."
+    fi
+    echo ""
+done
